server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: ${hostname:localhost}
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/